/** @format */

export const GET_COINS_REQUEST = "GET_COINS_REQUEST";
export const GET_COINS_SUCCESS = "GET_COINS_SUCCESS";
export const GET_COINS_FAIL = "GET_COINS_FAIL";

export const GET_COIN_DETAILS_REQUEST = "GET_COIN_DETAILS_REQUEST";
export const GET_COIN_DETAILS_SUCCESS = "GET_COIN_DETAILS_SUCCESS";
export const GET_COIN_DETAILS_FAIL = "GET_COIN_DETAILS_FAIL";

export const GET_COINS_CHART_REQUEST = "GET_COINS_CHART_REQUEST";
export const GET_COINS_CHART_SUCCESS = "GET_COINS_CHART_SUCCESS";
export const GET_COINS_CHART_FAIL = "GET_COINS_CHART_FAIL";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";

export const GET_EXCHANGE_RATES_REQUEST = "GET_EXCHANGE_RATES_REQUEST";
export const GET_EXCHANGE_RATES_SUCCESS = "GET_EXCHANGE_RATES_SUCCESS";
export const GET_EXCHANGE_RATES_FAIL = "GET_EXCHANGE_RATES_FAIL";

export const GET_EXCHANGES_REQUEST = "GET_EXCHANGES_REQUEST";
export const GET_EXCHANGES_SUCCESS = "GET_EXCHANGES_SUCCESS";
export const GET_EXCHANGES_FAIL = "GET_EXCHANGES_FAIL";

export const GET_STATUS_UPDATE_REQUEST = "GET_STATUS_UPDATE_REQUEST";
export const GET_STATUS_UPDATE_SUCCESS = "GET_STATUS_UPDATE_SUCCESS";
export const GET_STATUS_UPDATE_FAIL = "GET_STATUS_UPDATE_FAIL";

export const GET_GLOBAL_REQUEST = "GET_GLOBAL_REQUEST";
export const GET_GLOBAL_SUCCESS = "GET_GLOBAL_SUCCESS";
export const GET_GLOBAL_FAIL = "GET_GLOBAL_FAIL";

export const SET_NAVBAR_MENU_ITEM = "SET_NAVBAR_MENU_ITEM";
export const SET_SIDEBAR_MENU_ITEM = "SET_SIDEBAR_MENU_ITEM";
